# Generated by Django 4.1.7 on 2023-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product',
        ),
        migrations.AddField(
            model_name='collection',
            name='product',
            field=models.ManyToManyField(to='shop.product', verbose_name='Item'),
        ),
    ]
